//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_University_App_EntityFramework.DataLayer.EFLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public string CourseNum { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CreditHours { get; set; }
        public string Description { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    }
}
